const CSRC_SEARCH='https://www.csrc.gov.cn/guestweb4/s';
const EASTMONEY_FUND=code=>`https://fund.eastmoney.com/${encodeURIComponent(code)}.html`;
const CACHE_VERSION='v15-stable';
const TTL=6*60*60;
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Cache-Control':'no-store'};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json;charset=UTF-8',...CORS}});
function dec(s=''){return String(s).replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/&#x([\da-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16))).replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&#39;/g,"'")}
function clean(s=''){return dec(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function abs(h=''){try{return new URL(dec(h),'https://www.csrc.gov.cn').href}catch{return''}}
function dateOf(s=''){const m=String(s).match(/20\d{2}[-年\/.]\d{1,2}[-月\/.]\d{1,2}/);return m?m[0].replace(/[年月]/g,'-').replace(/\//g,'-').replace(/--/g,'-'):''}
function typeOf(s=''){if(/市场禁入|证券市场禁入/.test(s))return'市场禁入';if(/行政处罚|处罚决定书|行政处罚决定|罚款|没收违法所得/.test(s))return'行政处罚';if(/警示函|出具警示函/.test(s))return'警示函';if(/监管措施|责令改正|监管谈话|暂停.*业务|限制.*业务|整改/.test(s))return'监管措施';if(/纪律处分/.test(s))return'纪律处分';return''}
function level(t){return t==='行政处罚'||t==='市场禁入'?'high':'medium'}
function measure(s=''){const a=['市场禁入','罚款','没收违法所得','警示函','责令改正','监管谈话','暂停相关业务','限制业务活动','整改','纪律处分'];return[...new Set(a.filter(x=>s.includes(x)))].join('、')}
async function fetchText(url,ms=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.8','Accept-Language':'zh-CN,zh;q=0.9'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function params(q,p=1){return new URLSearchParams({siteCode:'bm56000001',checkHandle:'1',pageSize:'20',pageNum:String(p),searchWord:q,column:'全部',searchSource:'0',govWorkBean:'{}',countKey:'0',uc:'0',left_right_index:'0',orderBy:'2',wordPlace:'0'}).toString()}
function parse(html,query,manager,people){const out=[],seen=new Set(),re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const url=abs(m[1]),title=clean(m[2]);if(!url||!url.includes('csrc.gov.cn')||title.length<4||seen.has(url))continue;const ctx=clean(html.slice(Math.max(0,m.index-1000),Math.min(html.length,m.index+2400))),blob=title+' '+ctx,t=typeOf(blob);if(!t)continue;if(/培训|会议|讲座|宣传|活动|招聘|通知公告/.test(title)&&!/(行政处罚|警示函|监管措施|市场禁入|纪律处分)/.test(title))continue;const matched=manager&&blob.includes(manager)||people.some(x=>x&&blob.includes(x));if(!matched)continue;seen.add(url);out.push({title,url,date:dateOf(blob),type:t,level:level(t),agency:(blob.match(/中国证监会|[\u4e00-\u9fa5]{2,12}证监局/)||['中国证监会'])[0],subject:people.find(x=>x&&blob.includes(x))||manager,relation:people.some(x=>x&&blob.includes(x))?'基金经理关联记录':'基金管理人关联记录',summary:title,measure:measure(blob),result:''});if(out.length>=100)break}return out}
const MANAGERS=[['华夏','华夏基金管理有限公司'],['易方达','易方达基金管理有限公司'],['广发','广发基金管理有限公司'],['富国','富国基金管理有限公司'],['南方','南方基金管理股份有限公司'],['国泰','国泰基金管理有限公司'],['嘉实','嘉实基金管理有限公司'],['建信','建信基金管理有限责任公司'],['天弘','天弘基金管理有限公司'],['华宝','华宝基金管理有限公司'],['摩根','摩根基金管理（中国）有限公司'],['国富','国海富兰克林基金管理有限公司'],['万家','万家基金管理有限公司'],['浦银','浦银安盛基金管理有限公司'],['博时','博时基金管理有限公司'],['中欧','中欧基金管理有限公司'],['工银瑞信','工银瑞信基金管理有限公司'],['招商','招商基金管理有限公司'],['鹏华','鹏华基金管理有限公司'],['交银施罗德','交银施罗德基金管理有限公司'],['兴证全球','兴证全球基金管理有限公司'],['银华','银华基金管理股份有限公司'],['华安','华安基金管理有限公司'],['汇添富','汇添富基金管理股份有限公司'],['兴业','兴业基金管理有限公司'],['中银','中银基金管理有限公司'],['平安','平安基金管理有限公司'],['诺安','诺安基金管理有限公司'],['长城','长城基金管理有限公司'],['东方','东方基金管理股份有限公司'],['长信','长信基金管理有限责任公司'],['华泰柏瑞','华泰柏瑞基金管理有限公司'],['浙商','浙商基金管理有限公司'],['前海开源','前海开源基金管理有限公司']];
function managerFromName(n=''){return MANAGERS.find(x=>n.includes(x[0]))?.[1]||''}
function extractPeople(s=''){const a=[];for(const r of [/(?:基金经理|现任基金经理)[：:\s]{0,20}([\u4e00-\u9fa5]{2,6}(?:[、,，][\u4e00-\u9fa5]{2,6}){0,6})/g,/(?:经理)[：:\s]{0,10}([\u4e00-\u9fa5]{2,6})/g]){let m;while((m=r.exec(s)))a.push(...m[1].split(/[、,，]/).map(x=>x.trim()))}return[...new Set(a)].filter(x=>/^[\u4e00-\u9fa5]{2,6}$/.test(x)).slice(0,10)}
async function fundInfo(code,name){let manager=managerFromName(name),people=[],raw='';try{raw=await fetchText(EASTMONEY_FUND(code),5000);const s=clean(raw);if(!manager){const m=s.match(/(?:基金管理人|管理人)[：:\s]*([\u4e00-\u9fa5A-Za-z0-9（）()·\-]{4,120}基金管理(?:有限公司|股份有限公司|有限责任公司))/);if(m)manager=m[1].trim()}people=extractPeople(s)}catch{}return{manager,people}}
async function searchOne(q,p,manager,people){const html=await fetchText(`${CSRC_SEARCH}?${params(q,p)}`);return parse(html,q,manager,people)}
async function run(manager,people){const qs=[manager,...people].filter(Boolean),jobs=[];for(const q of qs)for(let p=1;p<=3;p++)jobs.push([q,p]);const out=[],errors=[];for(let i=0;i<jobs.length;i+=6){const rs=await Promise.allSettled(jobs.slice(i,i+6).map(x=>searchOne(x[0],x[1],manager,people)));for(const r of rs)r.status==='fulfilled'?out.push(...r.value):errors.push(r.reason)}return{out,errors,total:jobs.length}}
async function risk(req){const u=new URL(req.url),code=(u.searchParams.get('code')||'').replace(/\D/g,'').slice(0,6),name=u.searchParams.get('name')||'',force=u.searchParams.get('force')==='1';if(!code)return json({error:'missing code'},400);const key=new Request(new URL(`/api/risk?v=${CACHE_VERSION}&code=${code}`,u.origin));if(!force){const c=await caches.default.match(key);if(c){const d=await c.json();d.cached=true;return json(d)}}const info=await fundInfo(code,name);if(!info.manager)return json({ok:false,code,name,records:[],error:'无法识别基金管理人'},422);const r=await run(info.manager,info.people),seen=new Set(),records=r.out.filter(x=>{if(seen.has(x.url))return false;seen.add(x.url);return true}).sort((a,b)=>(b.date||'').localeCompare(a.date||''));const data={ok:true,code,name,manager:info.manager,managers:info.people,records,counts:records.reduce((a,x)=>(a[x.type]=(a[x.type]||0)+1,a),{}),updatedAt:new Date().toISOString(),source:'中国证券监督管理委员会公开信息检索',successfulJobs:r.total-r.errors.length,totalJobs:r.total};await caches.default.put(key,new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json;charset=UTF-8','Cache-Control':`public,max-age=${TTL}`}}));return json(data)}
export default{async fetch(request,env){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(u.pathname==='/api/risk'&&request.method==='GET')return risk(request);if(env.ASSETS)return env.ASSETS.fetch(request);return new Response('Fund PWA risk backend',{status:200,headers:{'Content-Type':'text/plain;charset=UTF-8'}})}};