const CSRC_SEARCH='https://www.csrc.gov.cn/guestweb4/s';
const EASTMONEY_FUND=code=>`https://fund.eastmoney.com/${encodeURIComponent(code)}.html`;
const CACHE_VERSION='v17-index';const TTL=12*60*60;
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Cache-Control':'no-store'};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json;charset=UTF-8',...CORS}});
function dec(s=''){return String(s).replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16))).replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&#39;/g,"'")}
function clean(s=''){return dec(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function abs(h=''){try{return new URL(dec(h),'https://www.csrc.gov.cn').href}catch{return''}}
function date(s=''){const m=String(s).match(/(20\d{2})[-年\/.](\d{1,2})[-月\/.](\d{1,2})/);return m?`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`:''}
function type(s){if(/市场禁入|证券市场禁入/.test(s))return'市场禁入';if(/行政处罚|处罚决定书|没收违法所得|罚款|行政处罚决定/.test(s))return'行政处罚';if(/纪律处分|纪律处分决定/.test(s))return'纪律处分';if(/警示函|出具警示函/.test(s))return'警示函';if(/监管措施|责令改正|监管谈话|暂不受理|暂停.*业务|限制.*业务|整改/.test(s))return'监管措施';return'其他'}
function level(t){return t==='行政处罚'||t==='市场禁入'?'high':t==='警示函'||t==='监管措施'||t==='纪律处分'?'medium':'low'}
function riskLike(s){return /行政处罚|处罚决定书|市场禁入|警示函|监管措施|责令改正|监管谈话|纪律处分/.test(s)}
function measure(s){return[...new Set(['责令改正','出具警示函','警示函','监管谈话','暂停相关业务','限制业务活动','市场禁入','行政处罚','罚款','纪律处分'].filter(x=>s.includes(x)))].join('、')}
function agency(s){return(s.match(/中国证监会|[\u4e00-\u9fa5]{2,12}证监局/)||['中国证监会'])[0]}
async function get(url,ms=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html,application/xhtml+xml,text/plain;q=0.9','Accept-Language':'zh-CN,zh;q=0.9'}});if(!r.ok)throw Error(`上游${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function params(term,p){return new URLSearchParams({siteCode:'bm56000001',checkHandle:'1',pageSize:'20',pageNum:String(p),searchWord:term,column:'全部',searchSource:'0',govWorkBean:'{}',countKey:'0',uc:'0',left_right_index:'0',orderBy:'2',wordPlace:'0'}).toString()}
function parse(html,query,relation){const out=[],re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const u=abs(m[1]),title=clean(m[2]);if(!u.includes('csrc.gov.cn')||title.length<4)continue;const context=clean(html.slice(Math.max(0,m.index-600),Math.min(html.length,m.index+900))),blob=`${title} ${context}`;if(!riskLike(blob)||!blob.includes(query))continue;const k=u+'|'+title;if(out.some(x=>x.key===k))continue;const t=type(blob);if(t==='其他')continue;out.push({key:k,title,url:u,date:date(blob),type:t,level:level(t),agency:agency(blob),subject:'',relation,summary:title,measure:measure(blob),result:'',query});if(out.length>=100)break}return out}
async function search(term,p,relation){return parse(await get(`${CSRC_SEARCH}?${params(term,p)}`),term,relation)}
const MANAGERS=[['华夏','华夏基金管理有限公司'],['易方达','易方达基金管理有限公司'],['广发','广发基金管理有限公司'],['富国','富国基金管理有限公司'],['南方','南方基金管理股份有限公司'],['国泰','国泰基金管理有限公司'],['嘉实','嘉实基金管理有限公司'],['建信','建信基金管理有限责任公司'],['天弘','天弘基金管理有限公司'],['华宝','华宝基金管理有限公司'],['摩根','摩根基金管理（中国）有限公司'],['国富','国海富兰克林基金管理有限公司'],['万家','万家基金管理有限公司'],['浦银','浦银安盛基金管理有限公司'],['博时','博时基金管理有限公司'],['中欧','中欧基金管理有限公司'],['工银瑞信','工银瑞信基金管理有限公司'],['招商','招商基金管理有限公司'],['鹏华','鹏华基金管理有限公司'],['交银施罗德','交银施罗德基金管理有限公司'],['兴证全球','兴证全球基金管理有限公司'],['银华','银华基金管理股份有限公司'],['华安','华安基金管理有限公司'],['汇添富','汇添富基金管理股份有限公司'],['兴业','兴业基金管理有限公司'],['中银','中银基金管理有限公司'],['平安','平安基金管理有限公司'],['诺安','诺安基金管理有限公司'],['长城','长城基金管理有限公司'],['东方','东方基金管理股份有限公司'],['长信','长信基金管理有限责任公司'],['华泰柏瑞','华泰柏瑞基金管理有限公司'],['浙商','浙商基金管理有限公司'],['前海开源','前海开源基金管理有限公司']];
function managerFromName(n=''){const x=MANAGERS.find(([k])=>String(n).includes(k));return x?x[1]:''}
function aliases(m=''){const a=[m],s=m.replace(/（中国）|\(中国\)/g,'').replace(/基金管理(有限公司|股份有限公司|有限责任公司)$/,'');if(s&&s!==m)a.push(s);if(m==='国海富兰克林基金管理有限公司')a.push('国富基金');if(m==='摩根基金管理（中国）有限公司')a.push('摩根基金');return[...new Set(a)]}
function managersFromHtml(raw=''){const t=clean(raw),out=[],re=/(?:基金经理|现任基金经理|拟任基金经理)[：:\s]{0,30}([\u4e00-\u9fa5]{2,6}(?:\s*[、,，]\s*[\u4e00-\u9fa5]{2,6}){0,8})/g;let m;while((m=re.exec(t)))out.push(...m[1].split(/[、,，]/).map(x=>x.trim()).filter(x=>/^[\u4e00-\u9fa5]{2,6}$/.test(x)));return[...new Set(out)].slice(0,10)}
async function fundInfo(code,name){let manager=managerFromName(name),managers=[],raw='';try{raw=await get(EASTMONEY_FUND(code),5000);const t=clean(raw);if(!manager){const m=t.match(/(?:基金管理人|管理人)[：:\s]*([\u4e00-\u9fa5A-Za-z0-9（）()·\-]{4,120}基金管理(?:有限公司|股份有限公司|有限责任公司))/);if(m)manager=m[1].trim()}managers=managersFromHtml(raw)}catch{}return{manager,managers}}
function norm(s=''){return String(s).replace(/[（）()\s]/g,'').toLowerCase()}
function subjectFrom(blob,manager,people){const p=people.find(x=>blob.includes(x));if(p)return `${p}（时任${manager}基金经理）`;const pm=blob.match(/(?:当事人|被处罚人|当事机构|相关责任人员)[：: ]{0,8}([^。；，,]{2,30})/);return pm?pm[1].trim():manager}
function related(r,manager,people,fund){const b=norm(`${r.title} ${r.summary} ${r.query}`),m=aliases(manager).map(norm),ps=people.map(norm),f=norm(fund);if(r.relation==='基金经理')return ps.some(x=>x.length>=2&&b.includes(x));if(r.relation==='基金产品')return !!f&&b.includes(f);return m.some(x=>x.length>=3&&b.includes(x))}
const INDEX_URL='https://risk-index.internal/v1/global';
async function loadIndex(){try{const c=await caches.default.match(INDEX_URL);if(c)return await c.json()}catch{}return {version:CACHE_VERSION,records:[],managers:{},updatedAt:''}}
async function saveIndex(i){await caches.default.put(INDEX_URL,new Response(JSON.stringify(i),{headers:{'Content-Type':'application/json','Cache-Control':'public,max-age=86400'}}))}
async function ensureGlobal(index,manager){if(!manager)return index;if(index.managers?.[manager]?.at&&Date.now()-Date.parse(index.managers[manager].at)<7*86400000)return index;const terms=[...aliases(manager)];const jobs=terms.flatMap(t=>[1,2,3,4].map(p=>search(t,p,'基金管理人')));const rs=await Promise.allSettled(jobs),map=new Map((index.records||[]).map(x=>[x.key,x]));for(const q of rs)if(q.status==='fulfilled')for(const r of q.value)map.set(r.key,r);index.records=[...map.values()].slice(-10000);index.managers=index.managers||{};index.managers[manager]={at:new Date().toISOString(),count:index.records.filter(r=>aliases(manager).some(a=>norm(`${r.title} ${r.query}`).includes(norm(a)))).length};index.version=CACHE_VERSION;index.updatedAt=new Date().toISOString();await saveIndex(index);return index}
async function risk(req){const u=new URL(req.url),code=(u.searchParams.get('code')||'').replace(/\D/g,'').slice(0,6),name=u.searchParams.get('name')||'',force=u.searchParams.get('force')==='1';if(!code)return json({error:'missing code'},400);const key=new Request(new URL(`/api/risk?v=${CACHE_VERSION}&code=${code}`,u.origin));if(!force){const c=await caches.default.match(key);if(c){const d=await c.json();d.cached=true;return json(d)}}const info=await fundInfo(code,name),manager=info.manager,people=info.managers;if(!manager)return json({ok:false,code,name,records:[],error:'无法识别基金管理人'},422);let index=await loadIndex();index=await ensureGlobal(index,manager);let records=(index.records||[]).filter(r=>related(r,manager,people,name)).map(r=>({...r,subject:subjectFrom(`${r.title} ${r.summary} ${r.query}`,manager,people)}));if(!records.length){const jobs=[...aliases(manager).flatMap(a=>[1,2].map(p=>search(a,p,'基金管理人'))),...people.flatMap(p=>[1,2].map(n=>search(p,n,'基金经理')))];const rs=await Promise.allSettled(jobs);for(const q of rs)if(q.status==='fulfilled')records.push(...q.value.filter(r=>related(r,manager,people,name)).map(r=>({...r,subject:subjectFrom(`${r.title} ${r.summary} ${r.query}`,manager,people)})))}const seen=new Set();records=records.filter(r=>{const k=r.url+'|'+r.title;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,300);const counts={};for(const r of records)counts[r.type]=(counts[r.type]||0)+1;const data={ok:true,code,name,manager,managers:people,records,counts,updatedAt:new Date().toISOString(),source:'中国证券监督管理委员会公开信息检索',indexed:true};await caches.default.put(key,new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json;charset=UTF-8','Cache-Control':`public,max-age=${TTL}`}}));return json(data)}
export default{async fetch(request,env){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(u.pathname==='/api/risk'&&request.method==='GET')return risk(request);if(u.pathname==='/api/risk-index'&&request.method==='GET'){const i=await loadIndex();return json({version:i.version,updatedAt:i.updatedAt,count:(i.records||[]).length,managers:Object.keys(i.managers||{}).length})}if(env.ASSETS)return env.ASSETS.fetch(request);return new Response('Fund PWA v17',{status:200,headers:{'Content-Type':'text/plain;charset=UTF-8'}})}};
